In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn import linear_model
import word2number
from word2number import w2n
import math

In [2]:
data = pd.read_csv("salary.csv")
data.head(15)

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [3]:
data.test_score.isna().any()

True

In [4]:
test_median = data.test_score.median()
test_median

8.0

In [5]:
data['test_score'].fillna(test_median , inplace = True)
data

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [6]:
print(w2n.word_to_num('four'))

4


In [7]:
data.experience.isna().any()

True

In [17]:
data.experience.fillna('zero', inplace=True)
data

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [18]:
data.experience = data.experience.apply(w2n.word_to_num)
data

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [24]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [28]:
lr.fit(data[['experience','test_score','interview_score']], data.salary)

LinearRegression()

In [30]:
lr.predict([[0, 6, 8]])

c:\users\yashr\appdata\local\programs\python\python38\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([46453.42066958])

In [31]:
lr.predict([[2,9,6]])


c:\users\yashr\appdata\local\programs\python\python38\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [32]:
lr.predict([[10,7,8]])

c:\users\yashr\appdata\local\programs\python\python38\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([76428.67540029])