In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [2]:
df = pd.read_csv('houseprediction.csv')
df.head(2)

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000

In [3]:
df.isna().any()

area        False
bedrooms     True
age         False
price       False
dtype: bool

In [4]:
df.isna().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

In [5]:
mean_bedroom = df.bedrooms.median()

print((mean_bedroom))

4.0


In [6]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [7]:
df.bedrooms.fillna(mean_bedroom, inplace=True)

In [8]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [10]:
model=LinearRegression()

In [11]:
x=df[['area','bedrooms','age']]
y=df.price

In [12]:
model.fit(x, y)

LinearRegression()

In [13]:
model.score(x,y)

0.9550196399325818

In [14]:
model.predict([['2600','3','20']])

c:\users\yashr\appdata\local\programs\python\python38\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
c:\users\yashr\appdata\local\programs\python\python38\lib\site-packages\sklearn\base.py:566: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)


array([518217.63297611])

In [15]:
model.predict([['3200','4','18']])

c:\users\yashr\appdata\local\programs\python\python38\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
c:\users\yashr\appdata\local\programs\python\python38\lib\site-packages\sklearn\base.py:566: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)


array([615307.4140366])

In [16]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [17]:
model.intercept_

221323.00186540443