# We will try with other methods like 
## Logistic, Random Forest, SVC

### then we will move on with K fold Method


In [1]:
import sklearn

In [2]:
from sklearn.linear_model import LogisticRegression 
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVR, SVC

In [3]:
lr = LogisticRegression()
rf = RandomForestClassifier()
svr = SVR()
svc =SVC()

In [4]:
import  numpy as np

In [5]:
from sklearn.datasets import load_digits

In [6]:
dg =load_digits()

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test,y_train,y_test = train_test_split(dg.data, dg.target, test_size=0.3)

In [9]:
#Linear Regression 
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

c:\users\yashr\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9555555555555556

In [10]:
#Random Forest Classifier
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9740740740740741

In [11]:
#Support Vector Machine
svr.fit(X_train,y_train)
svr.score(X_test,y_test)

0.8632063682997092

In [12]:
#Support Vector Machine
svc.fit(X_train,y_train)
svc.score(X_test,y_test)

0.987037037037037

# Now we will learn about K-Fold

In [13]:
from sklearn.model_selection import KFold

In [14]:
kf = KFold(n_splits =3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [15]:
#n_split is work in this type of process where you can split the data in multiple manners
for  train_index , test_index in kf.split ([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [18]:
def get_score(model, X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [19]:
get_score(LogisticRegression() , X_train,X_test, y_train,y_test)

c:\users\yashr\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9555555555555556

## Stratified K-Fold

In [22]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [23]:
score_l =[]
score_svm=[]
score_rf =[]

In [25]:
from sklearn.model_selection import cross_val_score

In [26]:
cross_val_score(LogisticRegression(), dg.data, dg.target)

c:\users\yashr\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\users\yashr\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stab

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [27]:
cross_val_score(SVC(), dg.data, dg.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [28]:
cross_val_score(RandomForestClassifier(), dg.data, dg.target)

array([0.93055556, 0.90555556, 0.95821727, 0.9637883 , 0.92200557])

In [29]:
cross_val_score(RandomForestClassifier(n_estimators=10), dg.data, dg.target)

array([0.89722222, 0.84444444, 0.90807799, 0.93593315, 0.88579387])

In [30]:
cross_val_score(RandomForestClassifier(n_estimators=50), dg.data, dg.target)

array([0.91944444, 0.90833333, 0.94150418, 0.96935933, 0.92200557])

In [31]:
cross_val_score(RandomForestClassifier(n_estimators=30), dg.data, dg.target)

array([0.90833333, 0.89166667, 0.94986072, 0.95264624, 0.90250696])